# Generated by Django 5.2.17 on 2026-08-31 09:33

import django.db.models.deletion
import django.utils.timezone
import workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.CharField(default=workflow.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_status', models.CharField(choices=[('discovered', 'Discovered'), ('hashing', 'Hashing'), ('routing', 'Routing'), ('needs_review', 'Needs Review'), ('ready_to_transcribe', 'Ready to Transcribe'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('failed', 'Failed')], default='discovered', max_length=32)),
                ('audio_status', models.CharField(choices=[('present', 'Present'), ('missing', 'Missing')], default='present', max_length=16)),
                ('failure_stage', models.CharField(blank=True, choices=[('ingest', 'Ingest'), ('routing', 'Routing'), ('transcription', 'Transcription')], default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('routing', 'Routing'), ('transcription', 'Transcription')], max_length=16)),
                ('ordinal', models.PositiveIntegerField()),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('language_arg', models.CharField(blank=True, max_length=32, null=True)),
                ('cli_args_json', models.JSONField(blank=True, default=list)),
                ('mw_version', models.CharField(blank=True, default='', max_length=64)),
                ('router_version', models.CharField(blank=True, default='', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('timeout', 'Timeout'), ('nonzero_exit', 'Non-zero Exit'), ('invalid_output', 'Invalid Output'), ('interrupted', 'Interrupted')], default='running', max_length=16)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='workflow.recording')),
            ],
            options={
                'ordering': ['recording', 'stage', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='AudioSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(help_text='Absolute, symlink-resolved path as first observed')),
                ('path_identity', models.TextField(db_index=True, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_mtime', models.FloatField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stable_since', models.DateTimeField(blank=True, null=True)),
                ('discovery_state', models.CharField(choices=[('observing', 'Observing stability'), ('hashing', 'Hashing'), ('hashed', 'Hashed'), ('failed', 'Hash failed')], default='observing', max_length=16)),
                ('presence', models.CharField(choices=[('present', 'Present'), ('missing', 'Missing')], default='present', max_length=16)),
                ('missing_at', models.DateTimeField(blank=True, null=True)),
                ('is_canonical', models.BooleanField(default=False)),
                ('discovery_note', models.CharField(blank=True, default='', max_length=255)),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='workflow.recording')),
            ],
            options={
                'ordering': ['first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('route_suggestion', models.CharField(max_length=32)),
                ('profile_name', models.CharField(max_length=64)),
                ('model_id', models.CharField(max_length=128)),
                ('language_arg', models.CharField(blank=True, max_length=32, null=True)),
                ('method', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=16)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('routing_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_decisions', to='workflow.recording')),
            ],
            options={
                'ordering': ['recording', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('text_normalized', models.TextField(blank=True, default='')),
                ('mw_json', models.JSONField(blank=True, null=True)),
                ('parser_version', models.CharField(default='1', max_length=16)),
                ('language_observed', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transcript', to='workflow.processingattempt')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='workflow.recording')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('start_ms', models.BigIntegerField(blank=True, null=True)),
                ('end_ms', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='workflow.transcript')),
            ],
            options={
                'ordering': ['transcript', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('start_ms', models.BigIntegerField(blank=True, null=True)),
                ('end_ms', models.BigIntegerField(blank=True, null=True)),
                ('speaker', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='workflow.transcript')),
            ],
            options={
                'ordering': ['transcript', 'ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='processingattempt',
            constraint=models.UniqueConstraint(fields=('recording', 'stage', 'ordinal'), name='uniq_attempt_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='processingattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('recording', 'stage'), name='uniq_unfinished_attempt'),
        ),
        migrations.AddConstraint(
            model_name='routingdecision',
            constraint=models.UniqueConstraint(fields=('recording', 'ordinal'), name='uniq_routing_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='routingdecision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('recording',), name='uniq_active_routing_decision'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('recording',), name='uniq_active_transcript'),
        ),
    ]
