# Generated by Django 5.2.17 on 2026-08-31 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='last_failed_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_for_recordings', to='workflow.processingattempt'),
        ),
        migrations.AddField(
            model_name='recording',
            name='retranscription_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('transcript', 'ordinal'), name='uniq_section_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.UniqueConstraint(fields=('transcript', 'ordinal'), name='uniq_segment_ordinal'),
        ),
    ]
