# Generated by Django 5.2.17 on 2026-08-31 17:53

import django.db.models.deletion
import django.utils.timezone
import workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_recording_last_failed_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, preserved from first synchronization', max_length=64)),
                ('name_key', models.CharField(db_index=True, help_text='NFC + strip + casefold identity', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_configured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='resummarization_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recording',
            name='summary_status',
            field=models.CharField(choices=[('not_ready', 'No Active Transcript'), ('missing', 'Missing'), ('current', 'Current'), ('failed', 'Failed')], default='not_ready', max_length=16),
        ),
        migrations.AlterField(
            model_name='processingattempt',
            name='outcome',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('timeout', 'Timeout'), ('nonzero_exit', 'Non-zero Exit'), ('invalid_output', 'Invalid Output'), ('interrupted', 'Interrupted'), ('unreachable', 'Endpoint Unavailable'), ('http_error', 'HTTP Error'), ('response_too_large', 'Response Too Large'), ('input_too_large', 'Input Too Large')], default='running', max_length=32),
        ),
        migrations.AlterField(
            model_name='processingattempt',
            name='stage',
            field=models.CharField(choices=[('routing', 'Routing'), ('transcription', 'Transcription'), ('summarization', 'Summarization')], max_length=16),
        ),
        migrations.AlterField(
            model_name='recording',
            name='failure_stage',
            field=models.CharField(blank=True, choices=[('ingest', 'Ingest'), ('routing', 'Routing'), ('transcription', 'Transcription'), ('summarization', 'Summarization')], default='', max_length=16),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.CharField(default=workflow.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('people', models.JSONField(blank=True, default=list)),
                ('organizations', models.JSONField(blank=True, default=list)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('suggested_tags_raw', models.JSONField(blank=True, default=dict)),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('llm_base_url', models.CharField(blank=True, default='', max_length=255)),
                ('prompt_version', models.CharField(default='1', max_length=16)),
                ('parser_version', models.CharField(default='1', max_length=16)),
                ('config_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('chunk_count', models.PositiveIntegerField(default=1)),
                ('input_characters', models.PositiveIntegerField(default=0)),
                ('input_truncated', models.BooleanField(default=False)),
                ('limits_used', models.JSONField(blank=True, default=dict)),
                ('generation_mode', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='summary', to='workflow.processingattempt')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='workflow.recording')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='workflow.section')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='workflow.transcript')),
            ],
            options={
                'ordering': ['recording', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='SummaryTagSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_by_model', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_suggestions', to='workflow.summary')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summary_suggestions', to='workflow.tag')),
            ],
            options={
                'ordering': ['summary', 'tag__name'],
            },
        ),
        migrations.CreateModel(
            name='TagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('suggested', 'Model Suggested'), ('manual', 'Manual'), ('confirmed', 'User Confirmed')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_assignments', to='workflow.recording')),
                ('source_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='workflow.summary')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workflow.tag')),
            ],
            options={
                'ordering': ['recording', 'tag__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('recording', 'ordinal'), name='uniq_summary_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('transcript', 'section'), name='uniq_active_summary_in_scope'),
        ),
        migrations.AddConstraint(
            model_name='summarytagsuggestion',
            constraint=models.UniqueConstraint(fields=('summary', 'tag'), name='uniq_summary_tag_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='tagassignment',
            constraint=models.UniqueConstraint(fields=('recording', 'tag'), name='uniq_tag_assignment'),
        ),
        migrations.AddConstraint(
            model_name='tagassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('recording', 'tag'), name='uniq_active_tag_assignment'),
        ),
    ]
