# Generated by Django 5.2.17 on 2026-08-31 20:35

from django.db import migrations, models


def backfill_model_deactivations(apps, schema_editor):
    """Historically, the only writer that deactivated TagAssignment rows
    was re-summarization materialization (model-driven), so every
    already-inactive row is attributed to "model" before the state
    constraint is enforced. MUST run before AddConstraint, otherwise
    legacy inactive rows (deactivated_by="") would violate it."""
    TagAssignment = apps.get_model("workflow", "TagAssignment")
    TagAssignment.objects.filter(is_active=False).update(deactivated_by="model")


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_backfill_summary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagassignment',
            name='deactivated_by',
            field=models.CharField(blank=True, choices=[('', 'Not deactivated'), ('model', 'Model'), ('user', 'User')], default='', max_length=16),
        ),
        migrations.RunPython(backfill_model_deactivations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tagassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deactivated_by', ''), ('is_active', True)), models.Q(('deactivated_by__in', ['user', 'model']), ('is_active', False)), _connector='OR'), name='chk_tagassignment_deactivation_state'),
        ),
    ]
