# Generated by Django 5.2.17 on 2026-09-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_tagassignment_deactivated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingattempt',
            name='context_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
