# Generated by Django 5.2.17 on 2026-09-11 18:01

"""Step 6.1 segmented versions: layout parent + topic Section shape.

Adds the immutable transcript-bound ``SegmentedVersion`` layout parent
and extends ``Section`` with a nullable ``segmented_version`` ownership
FK plus canonical half-open segment range fields. The global
``(transcript, ordinal)`` section uniqueness is replaced by two
conditional constraints:

- fixed sections (``segmented_version IS NULL``): ordinal 0 unique per
  transcript — existing whole-recording sections stay valid unchanged;
- topic sections (``segmented_version IS NOT NULL``): ordinal >= 1
  unique per segmented version (ordinals repeat across layout revisions).

A same-row shape CHECK enforces the two mutually exclusive alternatives.
No data migration/backfill: existing ordinal-0 rows migrate with layout
NULL, satisfying the fixed-section alternative.

Fully reversible. On reverse the layout/range metadata is dropped, but
topic sections may carry duplicate ordinals across revisions, so BEFORE
restoring the old global ``(transcript, ordinal)`` unique the reverse
deterministically renumbers topic ordinals per transcript to unique
positive values (migration-local code only; PK/FKs unchanged).
"""

import django.db.models.deletion
import django.utils.timezone
import workflow.models
from django.db import migrations, models


def _renumber_topic_ordinals_for_reverse(apps, schema_editor):
    """Deterministically renumber topic Section ordinals for reverse.

    Multiple segmented revisions can hold topic sections with the same
    ordinals (each is unique only per ``segmented_version``). Before the
    old global ``(transcript, ordinal)`` uniqueness is restored, assign
    every topic section of a transcript a unique positive ordinal in the
    deterministic order ``(transcript, layout revision, ordinal)``
    (revision is unique per transcript, so the order is total).
    Fixed ordinal-0 sections keep ordinal 0, so the renumbering never
    collides with them. PKs, FKs and titles are unchanged.
    """
    Section = apps.get_model("workflow", "Section")
    alias = schema_editor.connection.alias
    topic_sections = list(
        Section.objects.using(alias)
        .filter(segmented_version__isnull=False)
        .order_by("transcript_id", "segmented_version__revision", "ordinal")
    )
    current_transcript = None
    next_ordinal = 1
    for section in topic_sections:
        if section.transcript_id != current_transcript:
            current_transcript = section.transcript_id
            next_ordinal = 1
        if section.ordinal != next_ordinal:
            section.ordinal = next_ordinal
            section.save(using=alias, update_fields=["ordinal"])
        next_ordinal += 1


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_tag_definition_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentedVersion',
            fields=[
                ('id', models.CharField(default=workflow.models._uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('start_segment_ordinal', models.PositiveIntegerField()),
                ('end_segment_ordinal_exclusive', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['transcript', '-revision'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='section',
            name='uniq_section_ordinal',
        ),
        migrations.AddField(
            model_name='section',
            name='end_segment_ordinal_exclusive',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='start_segment_ordinal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentedversion',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmented_versions', to='workflow.transcript'),
        ),
        migrations.AddField(
            model_name='section',
            name='segmented_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='workflow.segmentedversion'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('segmented_version__isnull', True)), fields=('transcript', 'ordinal'), name='uniq_section_ordinal_fixed'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('segmented_version__isnull', False)), fields=('segmented_version', 'ordinal'), name='uniq_section_ordinal_topic'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_segment_ordinal_exclusive__isnull', True), ('ordinal', 0), ('segmented_version__isnull', True), ('start_segment_ordinal__isnull', True)), models.Q(('end_segment_ordinal_exclusive__gt', models.F('start_segment_ordinal')), ('end_segment_ordinal_exclusive__isnull', False), ('ordinal__gte', 1), ('segmented_version__isnull', False), ('start_segment_ordinal__isnull', False)), _connector='OR'), name='chk_section_shape_segmentation'),
        ),
        migrations.AddConstraint(
            model_name='segmentedversion',
            constraint=models.UniqueConstraint(fields=('transcript', 'revision'), name='uniq_segmented_version_revision'),
        ),
        migrations.AddConstraint(
            model_name='segmentedversion',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='chk_segmented_version_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='segmentedversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('transcript',), name='uniq_active_segmented_version'),
        ),
        migrations.AddConstraint(
            model_name='segmentedversion',
            constraint=models.CheckConstraint(condition=models.Q(('start_segment_ordinal__gte', 0), ('end_segment_ordinal_exclusive__gt', models.F('start_segment_ordinal'))), name='chk_segmented_version_range'),
        ),
        migrations.AddConstraint(
            model_name='segmentedversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activated_at__isnull', False), ('is_active', True), ('superseded_at__isnull', True)), models.Q(('activated_at__isnull', False), ('is_active', False), ('superseded_at__isnull', False)), _connector='OR'), name='chk_segmented_version_lifecycle_shape'),
        ),
        migrations.AddConstraint(
            model_name='segmentedversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('superseded_at__isnull', False), _negated=True), ('activated_at__lte', models.F('superseded_at')), _connector='OR'), name='chk_segmented_version_activated_before_superseded'),
        ),
        # Forward is a schema-only no-op; the reverse renumbers topic
        # ordinals BEFORE the old global (transcript, ordinal) unique is
        # restored, so reversing after multiple topic revisions never
        # fails on duplicate ordinals.
        migrations.RunPython(
            migrations.RunPython.noop,
            _renumber_topic_ordinals_for_reverse,
        ),
    ]
