# Generated by Django 5.2.17 on 2026-09-11 21:10

"""Step 6.2 section-scoped tag assignments (backend foundation).

Adds the nullable ``TagAssignment.section`` ownership FK (PROTECT) and
replaces the recording-only uniqueness constraints with two conditional
uniques:

- recording scope (``section IS NULL``): unique ``(recording, tag)`` —
  every existing row migrates unchanged with section NULL;
- section scope (``section IS NOT NULL``): unique ``(section, tag)``.

``recording`` remains a REQUIRED denormalized parent for both scopes.
No data migration/backfill and no network: existing rows are
recording-scoped by construction (the new column is NULL).

Fully reversible. On reverse the section column and the conditional
uniques are dropped; BEFORE the old global ``(recording, tag)``
uniqueness is restored, every section-only ``TagAssignment`` row is
deterministically DELETED (migration-local code; recording-scoped rows
are preserved untouched), so reversing a database that already holds
6.2 section assignments succeeds while keeping the recording
assignments intact.
"""

import django.db.models.deletion
from django.db import migrations, models


def _delete_section_scoped_assignments_for_reverse(apps, schema_editor):
    """Discard section-only TagAssignment rows before the old
    ``(recording, tag)`` unique is restored.

    Section-scoped rows (``section_id IS NOT NULL``) can duplicate a
    recording-scoped tag and would violate the restored global unique;
    they are 6.2 data that the old schema cannot represent. The delete is
    bounded and deterministic (one statement, no iteration), and it never
    touches recording-scoped rows.
    """
    TagAssignment = apps.get_model("workflow", "TagAssignment")
    alias = schema_editor.connection.alias
    TagAssignment.objects.using(alias).filter(section__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_segmentedversion_remove_section_uniq_section_ordinal_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tagassignment',
            name='uniq_tag_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='tagassignment',
            name='uniq_active_tag_assignment',
        ),
        migrations.AddField(
            model_name='tagassignment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_assignments', to='workflow.section'),
        ),
        migrations.AddConstraint(
            model_name='tagassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('recording', 'tag'), name='uniq_tag_assignment_recording'),
        ),
        migrations.AddConstraint(
            model_name='tagassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('section', 'tag'), name='uniq_tag_assignment_section'),
        ),
        # Forward is a schema-only no-op; the reverse deletes section-only
        # assignment rows BEFORE the old (recording, tag) unique is
        # restored, so reversing with 6.2 data succeeds while recording
        # assignments are preserved.
        migrations.RunPython(
            migrations.RunPython.noop,
            _delete_section_scoped_assignments_for_reverse,
        ),
    ]