# Generated by Django 5.2.17

"""Step 6.2a temporary split titles (display provenance).

Adds the ``Section.title_is_temporary`` Boolean (default False) flag:

- every EXISTING row migrates with False — pre-0013 topic titles are
  custom/user-owned by construction (the editor never auto-named a
  section before this migration);
- the editor/segmentation service marks NEW split-created sections with
  True only when the stored title is EXACTLY the server-derived
  ``Segment N of YYYYMMDDHHMM`` value (see
  ``workflow.services.segmentation``), so a True flag is bound to the
  derived title and can never be forged onto a custom title.

The flag is display-only provenance and changes no other table/column.
The migration is additive (one new column, one ALTER) and fully
reversible with zero data loss or migration-local code.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_remove_tagassignment_uniq_tag_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title_is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]