# Generated by Django 5.2.17

"""Reversible Recording archive (nullable ``archived_at``).

Adds ``Recording.archived_at`` (nullable timestamp, default NULL):

- every EXISTING row migrates as active (NULL);
- a non-null value marks a Recording archived: source audio, transcripts,
  summaries, tags, SearchDocuments/EmbeddingDocuments and history all stay
  physically stored and internally healthy, but the Recording is ineligible
  for every user-facing Library/search/Ask/Review result and for automatic
  pipeline work. Restore clears the field.
- Archival is NEVER source-file or row deletion.

The migration is additive (one new nullable column, one ALTER) and fully
reversible with zero data loss and no migration-local code.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_section_title_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
