# Generated by Django 5.2.17

"""Reversible per-Section archive (nullable ``archived_at``).

Adds ``Section.archived_at`` (nullable timestamp, default NULL):

- every EXISTING row migrates as active/unarchived (NULL);
- a non-null value on a TOPIC Section marks that individual Section
  archived: it is a visibility/eligibility marker, NOT layout deletion.
  The section, its summaries/tags/history, the SearchDocuments and
  EmbeddingDocuments and the source audio all stay physically stored and
  internally healthy. The canonical layout validator keeps treating an
  archived Section as structurally present; only the user-facing
  Library/search/Ask item scopes exclude it. Restore clears the field.
- Archival is NEVER source-file, layout or row deletion.

The migration is additive (one new nullable column, one ALTER) and fully
reversible with zero data loss and no migration-local code. It never
edits migration 0014 because a user may already have applied it.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_recording_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
